# This is a basic workflow to help you get started with Actions

name: Build and deploy to IPFS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Runs a single command using the runners shell
      - name: Build site with hugo
        run: hugo -D --minify
        
      # Runs a set of commands using the runners shell
      - name: publish to ipfs
        uses: mikeal/npx@v2.0.0
        env:
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.PINATA_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.PINATA_SECRET }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: dapla.net
          IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.docs.dapla.net
        with:
          args: -- ipfs-deploy -p pinata -d cloudflare $GITHUB_WORKSPACE/public
